# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajout_benevoles.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ajout_Benevoles(object):
    def setupUi(self, Ajout_Benevoles):
        Ajout_Benevoles.setObjectName("Ajout_Benevoles")
        Ajout_Benevoles.resize(381, 350)
        self.gridLayout = QtWidgets.QGridLayout(Ajout_Benevoles)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lnom = QtWidgets.QLabel(Ajout_Benevoles)
        self.lnom.setObjectName("lnom")
        self.horizontalLayout.addWidget(self.lnom)
        self.nom = QtWidgets.QLineEdit(Ajout_Benevoles)
        self.nom.setObjectName("nom")
        self.horizontalLayout.addWidget(self.nom)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcre1 = QtWidgets.QLabel(Ajout_Benevoles)
        self.lcre1.setObjectName("lcre1")
        self.horizontalLayout_2.addWidget(self.lcre1)
        self.cre1 = QtWidgets.QComboBox(Ajout_Benevoles)
        self.cre1.setObjectName("cre1")
        self.horizontalLayout_2.addWidget(self.cre1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lcre2 = QtWidgets.QLabel(Ajout_Benevoles)
        self.lcre2.setObjectName("lcre2")
        self.horizontalLayout_3.addWidget(self.lcre2)
        self.cre2 = QtWidgets.QComboBox(Ajout_Benevoles)
        self.cre2.setObjectName("cre2")
        self.horizontalLayout_3.addWidget(self.cre2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lcre3 = QtWidgets.QLabel(Ajout_Benevoles)
        self.lcre3.setObjectName("lcre3")
        self.horizontalLayout_4.addWidget(self.lcre3)
        self.cre3 = QtWidgets.QComboBox(Ajout_Benevoles)
        self.cre3.setObjectName("cre3")
        self.horizontalLayout_4.addWidget(self.cre3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lartisteV = QtWidgets.QLabel(Ajout_Benevoles)
        self.lartisteV.setObjectName("lartisteV")
        self.horizontalLayout_5.addWidget(self.lartisteV)
        self.artisteV = QtWidgets.QComboBox(Ajout_Benevoles)
        self.artisteV.setObjectName("artisteV")
        self.horizontalLayout_5.addWidget(self.artisteV)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lartisteS = QtWidgets.QLabel(Ajout_Benevoles)
        self.lartisteS.setObjectName("lartisteS")
        self.horizontalLayout_6.addWidget(self.lartisteS)
        self.artisteS = QtWidgets.QComboBox(Ajout_Benevoles)
        self.artisteS.setObjectName("artisteS")
        self.horizontalLayout_6.addWidget(self.artisteS)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lremarques = QtWidgets.QLabel(Ajout_Benevoles)
        self.lremarques.setObjectName("lremarques")
        self.horizontalLayout_7.addWidget(self.lremarques)
        self.remarques = QtWidgets.QLineEdit(Ajout_Benevoles)
        self.remarques.setObjectName("remarques")
        self.horizontalLayout_7.addWidget(self.remarques)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ok = QtWidgets.QPushButton(Ajout_Benevoles)
        self.ok.setObjectName("ok")
        self.horizontalLayout_8.addWidget(self.ok)
        self.annuler = QtWidgets.QPushButton(Ajout_Benevoles)
        self.annuler.setObjectName("annuler")
        self.horizontalLayout_8.addWidget(self.annuler)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)

        self.retranslateUi(Ajout_Benevoles)
        QtCore.QMetaObject.connectSlotsByName(Ajout_Benevoles)

    def retranslateUi(self, Ajout_Benevoles):
        _translate = QtCore.QCoreApplication.translate
        Ajout_Benevoles.setWindowTitle(_translate("Ajout_Benevoles", "Ajouter un benevole"))
        self.lnom.setText(_translate("Ajout_Benevoles", "Nom Prenom"))
        self.lcre1.setText(_translate("Ajout_Benevoles", "Catégorie de creneaux 1"))
        self.lcre2.setText(_translate("Ajout_Benevoles", "Catégorie de creneaux 2"))
        self.lcre3.setText(_translate("Ajout_Benevoles", "Catégorie de creneaux 3"))
        self.lartisteV.setText(_translate("Ajout_Benevoles", "Artiste du Vendredi"))
        self.lartisteS.setText(_translate("Ajout_Benevoles", "Artiste du Samedi"))
        self.lremarques.setText(_translate("Ajout_Benevoles", "Remarques"))
        self.ok.setText(_translate("Ajout_Benevoles", "Ok"))
        self.annuler.setText(_translate("Ajout_Benevoles", "Annuler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ajout_Benevoles = QtWidgets.QDialog()
    ui = Ui_Ajout_Benevoles()
    ui.setupUi(Ajout_Benevoles)
    Ajout_Benevoles.show()
    sys.exit(app.exec_())

